name: Organization PR Checks

on:
  workflow_call:  # enables reuse from other repos
    inputs:

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
