name: Organization CI Checks

on:
  workflow_call:  # enables reuse from other repos
    inputs:
permissions:
  pull-requests: write
  contents: read
jobs:
  semantic-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
